Send message directly from step instead of separate job

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -8,22 +8,44 @@ on:
         type: string
 
 jobs:
-  send-message:
-    name: Send update message to server
-    uses: nl-squad/nl-cod2-workflows/.github/workflows/send-server-message.yml@main
-    with:
-      profile: default
-      message: "^8[UPDATE] ^7Continous deployment ^9updated mod version"
-    secrets: inherit
-
   deploy:
     name: Deploy server files
     runs-on: ubuntu-latest
-    needs: send-message
 
     steps:
     - name: Checkout repository
       uses: actions/checkout@v2
+
+    - name: Send message to server
+      run: |
+        project_definition="project-definition.json"
+        if [ ! -f $project_definition ]; then
+            echo "Error: $project_definition doesn't exist."
+            exit 1
+        fi
+
+        function extract_value_or_exit() {
+          local key=$1
+          local value=$(jq -r "$key" "$project_definition")
+
+          if [ "$value" = "null" ]; then
+              echo "Error: $key not found in the $project_definition file."
+              exit 1
+          fi
+
+          echo "$value"
+        }
+
+        ###
+
+        profile=${{ inputs.profile }}
+        rcon=$(extract_value_or_exit ".profiles.\"$profile\".cod2.rconPassword") || { echo "Skipping - no rcon password found"; exit 0; }
+        cod2_port=$(extract_value_or_exit ".profiles.\"$profile\".cod2.port") || { echo "Skipping - no cod2 port found"; exit 0; }
+        connection_address=$(extract_value_or_exit '.connection.address')
+
+        cmd="say ^8[UPDATE] ^7Continous deployment ^9updated mod version"
+        echo "Executing command '$cmd' for server $connection_address:$cod2_port"
+        echo -n -e "\xff\xff\xff\xffrcon $rcon $cmd" | nc -u -w 2 $connection_address $cod2_port
 
     - name: Deploy server files
       run: |
